# Generated by Django 2.2.11 on 2020-04-07 01:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientID', models.IntegerField()),
                ('clientName', models.CharField(max_length=30)),
                ('clientType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelNumber', models.IntegerField()),
                ('productName', models.CharField(max_length=30)),
                ('cellTechnology', models.CharField(max_length=30)),
                ('cellManufacturer', models.CharField(max_length=30)),
                ('numberOfCells', models.IntegerField()),
                ('numberOfCellsInSeries', models.IntegerField()),
                ('numberOfSeriesInString', models.IntegerField()),
                ('numberOfDiodes', models.IntegerField()),
                ('productLength', models.IntegerField()),
                ('productWidth', models.IntegerField()),
                ('productWeight', models.IntegerField()),
                ('superstateType', models.CharField(max_length=30)),
                ('superstateManufacturer', models.CharField(max_length=30)),
                ('frameType', models.CharField(max_length=30)),
                ('frameAdhesive', models.CharField(max_length=30)),
                ('encapsulateType', models.CharField(max_length=30)),
                ('encapsulantManufacturer', models.CharField(max_length=30)),
                ('junctionBoxType', models.CharField(max_length=30)),
                ('junctionBoxManufacturer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequenceID', models.IntegerField()),
                ('sequenceName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TestStandard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standardID', models.IntegerField()),
                ('standardName', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('publishedDate', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='certID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='issueDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='reportNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30)),
                ('jobTitle', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('officePhone', models.CharField(max_length=30)),
                ('cellPhone', models.CharField(max_length=30)),
                ('prefix', models.CharField(max_length=30)),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceID', models.IntegerField()),
                ('serviceName', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('isFIRequired', models.CharField(max_length=30)),
                ('fIFrequency', models.IntegerField()),
                ('standardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TestStandard')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxSystemVoltage', models.IntegerField()),
                ('voc', models.IntegerField()),
                ('isc', models.IntegerField()),
                ('vmp', models.IntegerField()),
                ('imp', models.IntegerField()),
                ('pmp', models.IntegerField()),
                ('ff', models.IntegerField()),
                ('modelNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('sequenceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TestSequence')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationID', models.IntegerField()),
                ('address1', models.CharField(max_length=30)),
                ('address2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('postalCode', models.IntegerField()),
                ('country', models.CharField(max_length=30)),
                ('phoneNumber', models.IntegerField()),
                ('faxNumber', models.IntegerField()),
                ('clientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Client')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='locationID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='modelNumber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='standardID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.TestStandard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.Users'),
            preserve_default=False,
        ),
    ]
